travis:
  secure:
    BINSTAR_TOKEN: EdwBka5WOjzAbOACRi2XEu6Npa0JdAsbenjAploWUn3v9yBL6NHzuzeMrb9jUbzKdLIZ7wVc1vpd02msOovUDwuCnIQwNu9rfSOlQWmVCGVLbhuEXoBUyP9WE/yMnzgeDhTtoQjwcdWU+A9E5Cgp9YXXbys/wn894+b2LME5Y1DeXdfisez5hJflJ1QRzk/4UyX+TqEJ1zvB++P6oVuKFeUit8bDscmSGYT+eQ0fQ1I9F6tj8Y8HnuoYK5DGw5GkCAQ9hTeHaOMKvZfeu8K89T+9m+YDTMdYhLbWbMV7J1bCI9/dxlOd4NvURBaYMAcgzXeDnIP0RURWQIfZOMJljwRUDbP0AssiYG5+DbhmRVSYc+NaRamRgZ0zk3tlTehTDw4oWtU19IY9SGvq1wfNX2ObfrywDFZYxOXZLQrZQGOIFpcf3wx4qRmk2BMgK6+8tstPsgsRSVraOoIwgemPKq1fkvCLBz13TfLZu2EB1trUY1tNdovXlT4OyibBZi2uLLXnHyzE4ZKELyer1tJMrrV7M2nFgPPTjSmbUQ4FKsK24UHy68XWuw1TWT2M9f2vS1XU4qFclTnLlHcNm6DEBk4MHEeFz2YPzCaNxI4OkCugay3LJxh1Uz98LpUPIcG5pLLwyk4A4J44Rn5o/Scg/Y5cPePweXOLw9gspCqbYT0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
