travis:
  secure:
    BINSTAR_TOKEN: SEITrOKc7GUMFoTkVKwyzWOpx+SBMI+PGGc8aQDoR/hwtk51s6Yk+YOAtuS795LjEa6+p06CdUtJAqeW/siH4dpffArD8jwnOBBnRxfGvnhLqu3PEB69KitUynt0knxGqo7mloX6EqHsGirbIHCLxlATwNyztbtAUUZycEF+Ciu/A1FCmuW77qpognG2iuH6qr0F5l9gEwze9sXZV7HGfdpHXJSvckHmwdJnDyqj9/sL8IiFDhl4qEW7Wud4hfx8aBVO4D/JNp9GW3rkx7DH4NydzLKIjM4kLAV577pWTbXuNxo91vsq9BKggOdHV8yrEo0jZQaNzab/Jb0ozoWQOQXsjX3v2C/bm9B6l3iNvwS6LGPxv/Ci/Dqml4SHfI+7vqts5kNl7egp5b/QrqHyum/HMQI/mnJwXR5U74TcRypCIpHexKEQ/ACDqDJMs2TT27g2lfk1MdUd8pbVAUQ5yRgAH8U5ITxVF0XrlW0zRcXtLSJfrhlXjceZfL8eljq1tDfoyDRcrcYHt7KrlO/W0ayS+5GjKe0zFryfqHaQ+njt8s5J8/byjEwkTeqv/qLFsOPEeTeYW5PGGGH77tKlmyl85ps4AAr/LK/kXfsk2YhRRt3dh9IJdxaDj5zrKxU6D8FRmvUQbDFe57TfLe3FVUxWZpSlz7b/qqMg5ERbnw0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
